-- customer
CREATE TABLE customer
(
customer_id INT GENERATED BY DEFAULT AS IDENTITY,
first_name varchar2(200),
last_name varchar2(200),
phone_number varchar2(20),
constraint pk_customer_id primary key (customer_id)
);

--old customer's constraints dropped
drop table customer CASCADE constraints;

insert into customer (first_name, last_name, phone_number) values ('joni','orziqov','998900121415');
insert into customer (first_name, last_name, phone_number) values ('nozima','saidova','9989001544545');
insert into customer (first_name, last_name, phone_number) values ('nozim','umrzoqov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('madina','umrzoqov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('nodir','akromov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('kamol','umirov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('kamola','nurdinov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('alibek','nuriddinov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('alisa','bozorov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('angelina','eshmirzayev','998944302044');
insert into customer (first_name, last_name, phone_number) values ('ikrom','oroqov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('ravshan','shuhratov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('laylo','nazirov','998944302044');
insert into customer (first_name, last_name, phone_number) values ('lola','istamov','998944302044');

select * from customer 
order by customer_id, customer_id 
FETCH FIRST 5 ROWS ONLY;

select count(*) from customer;

select distinct first_name from customer;

-- CREATE INSERT PROCEDURE
CREATE OR REPLACE PROCEDURE "insertcustomer"
(first_name In VARCHAR2,
 last_name IN VARCHAR2,
 phone_number IN VARCHAR2
 )
IS
BEGIN

INSERT INTO customer (FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ( first_name, last_name, phone_number);

END;
/

EXECUTE "insertcustomer";

BEGIN
 "insertcustomer"('joni', 'malikov', '900141718');
END;
/

SELECT * FROM CUSTOMER;



 

update customer 
set last_name = 'zokirov', phone_number = '998951252624' 
where customer_id = 3;



--delivery_driver
CREATE TABLE delivery_driver
(
delivery_driver_id int GENERATED BY DEFAULT AS IDENTITY,
first_name varchar2(200),
last_name varchar2(200),
phone_number varchar2(20),
constraint pk_delivery_driver_id primary key (delivery_driver_id)
);

insert into delivery_driver (first_name, last_name, phone_number) values ('johon','toshpolatov','998909002909');
insert into delivery_driver (first_name, last_name, phone_number) values ('nozim','jonibekov','998901444555');
insert into delivery_driver (first_name, last_name, phone_number) values ('ruslan','sardorov','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('malik','safari','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('husan','nozim','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('hasan','salimov','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('nodir','alisherov','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('mirpolat','mullaboyev','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('polat','omon','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('latif','ikromov','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('farhod','nazirov','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('akbar','lTIPOV','998901255898');
insert into delivery_driver (first_name, last_name, phone_number) values ('andrey','ivanovich','998901255898');

select * from delivery_driver;

--finding DUPLICATE VALUES 
SELECT last_name, count(*) 
FROM delivery_driver 
GROUP BY last_name
having count (*) > 1;

-- deleting DUPLICATE VALUES
DELETE FROM delivery_driver
WHERE ROWID NOT IN 
(SELECT MAX(ROWID) FROM delivery_driver GROUP BY FIRST_NAME);





CREATE TABLE address
(
address_id int generated always as identity,
tuman varchar2(200),
kocha varchar2(200),
dom_raqam varchar2(20),
hona_raqam int,
constraint pk_address_id primary key (address_id)
);

insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('mirobod','baynalminal','12', 23);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('shayhontohur','nozimiy','1b', 20);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('mirobod','abdulla qahhor','4c', 12);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('qorgontepa','malikiy','13e', 55);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('chilonzor','nizomiy','15', 12);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('kokaldosh','malikiy','12', 11);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('yunusobod','al-buhoriy','47', 12);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('mirobod','malikiy','15', 12);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('yunusobod','kunduziy','98', 44);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('bektemir','malikiy','12', 34);
insert into address (tuman, kocha, dom_raqam, hona_raqam) values ('yunusobod','oqariq','17c', 23);
commit;

--rename column name
Alter table address 
rename column 
dom_raqam to kocha_raqam;

select * from address;
select * from customer order by customer_id;

CREATE TABLE address_customer
(
address_customer_id int,
customer_id int,
address_id,
constraint pk_address_customer_id primary key (address_customer_id),
constraint fk_customer_id foreign key (customer_id) references customer(customer_id),
constraint fk_address_id foreign key (address_id) references address(address_id)
);


insert into address_customer values (1, 2,1);
insert into address_customer values (2, 3,2);
insert into address_customer values (3, 2,3);
insert into address_customer values (4, 19,25);
insert into address_customer values (5, 20,23);
insert into address_customer values (6, 23,3);
insert into address_customer values (7, 25,2);
insert into address_customer values (8, 29,24);
insert into address_customer values (9, 36,28);
insert into address_customer values (10, 37,25);
insert into address_customer values (11, 38,26);
insert into address_customer values (12, 61,24);
insert into address_customer values (13, 64,21);
insert into address_customer values (14, 65,22);
insert into address_customer values (15, 66,27);
insert into address_customer values (16, 67,28);



select 
DISTINCT customer_id, address_id
from address_customer;

select * from customer;
select * from address;
select * from address_customer;

--INNER JOIN
SELECT c.first_name, c.last_name, a.tuman, a.kocha, a.kocha_raqam, a.hona_raqam
FROM address_customer ac
JOIN customer c ON c.customer_id = ac.address_customer_id
JOIN address a ON a.address_id = ac.address_customer_id;

-- FULL OUTER JOIN
SELECT c.first_name, c.last_name, a.tuman, a.kocha, a.kocha_raqam, a.hona_raqam
FROM address_customer ac
FULL OUTER JOIN customer c ON c.customer_id = ac.address_customer_id
FULL OUTER JOIN  address a ON a.address_id = ac.address_customer_id;

-- LEFT OUTER JOIN
SELECT c.first_name, c.last_name, a.tuman, a.kocha, a.kocha_raqam, a.hona_raqam
FROM address_customer ac
LEFT OUTER JOIN customer c ON c.customer_id = ac.address_customer_id
LEFT OUTER JOIN  address a ON a.address_id = ac.address_customer_id;

-- RIGHT OUTER JOIN
SELECT c.first_name, c.last_name, a.tuman, a.kocha, a.kocha_raqam, a.hona_raqam
FROM address_customer ac
RIGHT OUTER JOIN customer c ON c.customer_id = ac.address_customer_id
RIGHT OUTER JOIN  address a ON a.address_id = ac.address_customer_id;





CREATE TABLE restaurant
(
id int generated always as identity,
name varchar2(100),
constraint pk_restaurant_id primary key (id)
);

insert into restaurant (name) values ('basribaba');
insert into restaurant (name) values ('oqtepa');
insert into restaurant (name) values ('max way');
insert into restaurant (name) values ('OQTEPA C5');
insert into restaurant (name) values ('GRAND');
insert into restaurant (name) values ('TANHO');
insert into restaurant (name) values ('MADINA');
insert into restaurant (name) values ('BASRI BABA magic city');
insert into restaurant (name) values ('CRYSTALE');
insert into restaurant (name) values ('SHEDEVR');
insert into restaurant (name) values ('BESH QOZON');


select * from restaurant;

CREATE TABLE menu_item
(
menu_item_id int generated always as identity,
name varchar2(200),
restaurant_id int,
constraint pk_menu_item_id primary key(menu_item_id),
constraint fk_restaurant_id foreign key (restaurant_id) references restaurant(id)
);


insert into menu_item (name, restaurant_id) values ('osh', 3);
insert into menu_item (name, restaurant_id) values ('norin', 4);
insert into menu_item (name, restaurant_id) values ('clab sandvich', 2);
insert into menu_item (name, restaurant_id) values ('oqtepa lavash', 1);
insert into menu_item (name, restaurant_id) values ('denov somsa', 4);
insert into menu_item (name, restaurant_id) values ('lagmon', 24);
insert into menu_item (name, restaurant_id) values ('shorva', 23);
insert into menu_item (name, restaurant_id) values ('bishteks', 22);
insert into menu_item (name, restaurant_id) values ('norin', 24);
insert into menu_item (name, restaurant_id) values ('fri', 26);
insert into menu_item (name, restaurant_id) values ('chuchvara', 28);

select * from menu_item;



CREATE TABLE orderr
(
orderr_id int generated always as identity,
customer_id int not null,
restaurant_id int not null,
address_customer_id int,
delivery_driver_id int not null,
order_datetime timestamp,
delivery_fee float,
total_amount float,
requested_delivery_datetime timestamp,
driver_rating int, 
restaurant_rating int,
constraint pk_order_id primary key (orderr_id),
constraint fk_customer_id_o foreign key (customer_id) references customer(customer_id),
constraint fk_address_customer_id_o foreign key (address_customer_id) references address_customer(address_customer_id),
constraint fk_delivery_driver_o foreign key (delivery_driver_id) references delivery_driver(delivery_driver_id)
);

insert into orderr ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 2, 3, 2, 3, '11-jan-2018 11:14:23.11', 14, 35, '11-jan-2018 11:14:23.11',4,4);
insert into orderr ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 1, 2, 3, 1, '24-feb-2018 11:14:23.11', 21, 32, '11-jan-2018 11:14:23.11',5,5);
insert into orderr ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 1, 3, 2, 3, '11-jan-2018 11:14:23.11', 14, 35, '11-jan-2018 11:14:23.11',4,3);

insert into orders ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 20, 24, 10, 29, '11-jan-2018 11:14:23.11', 14, 35, '11-jan-2018 11:14:23.11',4,3);
insert into orders ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 23, 25, 15, 27, '11-jan-2018 11:14:23.11', 14, 35, '11-jan-2018 11:14:23.11',4,3);
insert into orders ( customer_id, restaurant_id, address_customer_id, delivery_driver_id, order_datetime, delivery_fee, 
total_amount, requested_delivery_datetime, driver_rating, restaurant_rating)
values ( 61, 26, 16, 30, '11-jan-2018 11:14:23.11', 14, 35, '11-jan-2018 11:14:23.11',4,3);
 
select * from orders;
select * from restaurant;
alter table orders rename column orderr_id to orders_id;

--creating VIEW AND USING MULTIPLE JOINS
CREATE VIEW full_orders
AS 
SELECT 
c.first_name as customer_name,
c.phone_number as customer_phone_number,
r.name as restaurant_name,
dd.first_name as delivery_driver_name,
dd.phone_number as delivery_driver_phone_number,
o.order_datetime,
o.delivery_fee,
o.total_amount,
o.driver_rating,
o.restaurant_rating
FROM orders o
JOIN customer c ON o.customer_id = c.customer_id
JOIN restaurant r ON o.restaurant_id = r.id
JOIN delivery_driver dd ON o.delivery_driver_id = dd.delivery_driver_id;

select * from customer;
DROP TABLE orders;
ROLLBACK;

ALTER TABLE orderr 
RENAME TO orders;

CREATE TABLE order_menu_item
(
order_menu_item_id int generated always as identity,
menu_item_id int,
orderr_id int,
quantity_order int,
constraint pk_order_menu_item_id primary key (order_menu_item_id),
constraint fk_orderr_id foreign key (orderr_id) references orderr(orderr_id),
constraint fk_menu_item_id foreign key (menu_item_id) references menu_item(menu_item_id)
);


insert into order_menu_item (menu_item_id, orderr_id, quantity_order) values (2, 3, 5);
insert into order_menu_item (menu_item_id, orderr_id, quantity_order) values (3, 3, 2);
insert into order_menu_item (menu_item_id, orderr_id, quantity_order) values (1, 1, 3);
insert into order_menu_item (menu_item_id, orderr_id, quantity_order) values (2, 3, 4);

--GETTING CURRENT DATE TIME
SELECT
  TRUNC(CURRENT_DATE) AS current_date
FROM dual;

SELECT
  TO_CHAR(CURRENT_DATE, 'yyyy-MM-dd') AS current_date
FROM dual;

select sysdate from dual;
------------------------------


insert into customer (first_name, last_name, phone_number) values ('nodir','hayitov','998944435313');
COMMIT;
select * from customer;
delete from customer where customer_id = 3;


